name: Deploy a Cloud Function
on:
  release:
    types: [created]
    
jobs:
  deploy-setup:
    runs-on: 'ubuntu-latest'
    environment: "Google Cloud"
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

    - id: 'deploy-stonks'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'stonksbot'
        entry_point: 'discord_webhook'
        runtime: 'python310'
        project_id: ${{secrets.GCLOUD_PROJECT_ID}}
        env_vars: "PROJECT_ID=${{secrets.GCLOUD_PROJECT_NUM}},DISCORD_APPLICATION_ID=${{vars.DISCORD_APPLICATION_ID}}"
        timeout: 540

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'

  deploy-stonks:
    runs-on: 'ubuntu-latest'
    environment: "Google Cloud"
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

    - id: 'deploy-setup'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'setup'
        entry_point: 'register_bot'
        runtime: 'python310'
        project_id: ${{secrets.GCLOUD_PROJECT_ID}}
        env_vars: "PROJECT_ID=${{secrets.GCLOUD_PROJECT_NUM}},DISCORD_APPLICATION_ID=${{vars.DISCORD_APPLICATION_ID}}"
        timeout: 540

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
