name: Deploy a Cloud Function
on:
  release:
    types: [created]
    
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    environment: "Google Cloud"
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'setup'
        runtime: 'python310'
        project_id: ${{secrets.GCLOUD_PROJECT_ID}}
        env_vars: "PROJECT_ID=${{secrets.GCLOUD_PROJECT_NUM}}"

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
